version: "3.8"
services:
  libreasy:
    build: .
    container_name: libreasy
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    image: truebad0ur/libreasy:v0.3.0
    volumes:
      - ./books:/app/books
      - ./assets:/app/assets
      - ./css:/app/css
      - ./templates:/app/templates
